version: '3'
services:
  mysql:
    image: mariadb:latest
    container_name: mariadb-server-develop
    command: --max_allowed_packet=256M
    volumes:
      - "/home/docker/mysql/bancodedados:/var/lib/mysql:delegated"
    ports:
       - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    network_mode: 'bridge'
    restart: always
    
  litespeed:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    container_name: openlitespeed-develop
    env_file:
      - .env
    volumes:
        - ./lsws/conf:/usr/local/lsws/conf
        - ./lsws/admin-conf:/usr/local/lsws/admin/conf
        - ./bin/container:/usr/local/bin
        - ./sites:/var/www/vhosts/
        - ./acme:/root/.acme.sh/
        - ./logs:/usr/local/lsws/logs/
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 7080:7080
    restart: always
    environment:
      TZ: ${TimeZone}
    network_mode: 'bridge'
    restart: always
    links: 
      - 'mysql'
  phpmyadmin:
    # Para acessar http://localhost:8080
    # usuario root:${MYSQL_ROOT_PASSWORD}
    image: bitnami/phpmyadmin:5.0.2-debian-10-r72
    container_name: phpmyadmin-develop
    ports:
      - 8080:80
      - 8443:443
    environment:
        DATABASE_HOST: mysql
    network_mode: 'bridge'
    restart: always
    links: 
      - 'mysql'
